"use client";

import "bootstrap/dist/css/bootstrap.css";
import "./globals.scss";
import "../lib/utils/reset.css";
import Head from "next/head";
// import { NextUIProvider } from '@nextui-org/react'
import NavBar from "./(components)/NavBar/NavBar";

import { Roboto } from "next/font/google";
import { useEffect } from "react";

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script
          src="https://kit.fontawesome.com/e2115fd39c.js"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <body>
        <NavBar linkNames={["home", "recipes"]} />
        {children}
      </body>
    </html>
  );
}
